# -*- coding: utf-8 -*-
"""TA_Internshipipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hindbw0TayRhrfh-VuW-fhGUs4CvBU-f
"""

def print_pattern(n):
	k = 2*n - 2
	for i in range(0, n):
		for j in range(0, k):
			print(end=" ")

		k = k - 2
		for j in range(0, i+1):
			print("* ", end="")
		print("\r")



print_pattern(5)




n = 5
num = 65
for i in range(0, n):
  for j in range(0, i+1):
    ch = chr(num)
    print(ch, end=" ")
    num = num +1
  print("")









import re
 budget = float(input("Please Enter your budget"))
 Item ={}
 while(budget):
  temp = int(input("Enter your choice\n1.Add an item\n2.Exit "))
  if temp == 1:
    p_name = input("Enter product Name : ")
    p_qty =  input("Enter Quantity : ")
    p_qty = re.findall(r'\d+(?:\.\d+)?', p_qty)
    p_qty = float(p_qty[0])
    p_price = float(input("Enter Price : "))
    if (p_price>budget):
      print("Can't buy. Out of Budget\nBudget Left = ",budget)
    else:
      if p_name not in Item.keys():
        Item[p_name] = []
        Item[p_name].append(p_qty)
        Item[p_name].append(p_price)
        unit_cost = float(p_price / p_qty)
        Item[p_name].append(unit_cost)

      else:
        Item[p_name][0] = Item[p_name][0] + p_qty
        #Item[p_name][2] = Item[p_name][0] + p_qty

      budget = budget - (Item[p_name][2]*p_qty)
    print("Amount Left = ",budget)
  elif temp == 2:
    print("Amount left can buy you any of")
    for i in Item:
      if Item[i][2]<budget :
        print(i)
    break

print(Item)

print("Product Name","       ","Quantity","   ","Price","      ","Unit Cost" )
for k, v in Item.items():
    lang, perc, change = v
    print ("{:<20} {:<10} {:<10} {:<10}".format(k, lang, perc, change))

